version: '3'

services:
  hadoop-master:
    image: totofunku/bigdata-cours:latest
    container_name: hadoop-master
    hostname: hadoop-master
    networks:
      - hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
    command: /bin/bash -c "./start-hadoop.sh"

  hadoop-slave1:
    image: totofunku/bigdata-cours:latest
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    networks:
      - hadoop
    ports:
      - "8040:8042"

  hadoop-slave2:
    image: totofunku/bigdata-cours:latest
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    networks:
      - hadoop
    ports:
      - "8041:8042"

networks:
  hadoop:
    driver: bridge
